[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "ising2D"
version = "0.1"
requires-python = ">=3.8"

[project.optional-dependencies]
test = [
    "pytest",
]

[tool.ruff]
select = [
    "E","F", "W",
    "B",
    "I",
    "RUF",
    "UP",
]
